services:
  app:
    build: .
    container_name: dtv_schedule_rss
    ports:
      - "8000:80"
    environment:
      - UVICORN_ROOT_PATH=/
      - UVICORN_PROXY_HEADERS=true
      - UVICORN_FORWARDED_ALLOW_IPS=*
